### PR TITLE
Added support for Puppet 5

### PR DESCRIPTION
**Pull request by nick-markowski**
- Added travis check for ruby 2.4.4 and puppet 5.X
- Removed gem puppet-lint-appends-check and puppet-lint-usascii_format-check
  from the Gemfile, due to their dependency on puppet-lint 1.0.  The latest
  puppetlabs spec helper requires puppet-lint 2.0.
- Added inifile fixture
- Matched travis.yml vars with Gemfile logic

### CODE REVIEW

**Comment by cristifalcas** [comment]
Thank you @nick-markowski .

If you are interested, you can take ownership of this module, since I'm not working with puppet anymore. If you agree, I will put a banner on my page to let people know this is unmaintained and link to your project.

**Comment by nick-markowski** [comment]
@cristifalcas I'd like to wrap this module in with the simp project if that's ok

**Comment by cristifalcas** [comment]
Hi @nick-markowski . Sure, use it as you like.

**Comment by trevor-vaughan** [comment]
@cristifalcas Thanks for creating the module and letting us pull it in. If you don't mind, I'll let you know when we've fully forked it so that you can post a deprecation update to the Forge if that works for you.

**Comment by cristifalcas** [comment]
OK.I'll wait for your message

**Pull request merged**
